import { Inter } from "next/font/google";

import '@/app/globals.css';

import { Montserrat } from 'next/font/google'

//👇 Configure our font object
const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
